/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gwxtogwhpurxwjlfyftw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3eHRvZ3docHVyeHdqbGZ5ZnR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMjA0MDksImV4cCI6MjA3NTY5NjQwOX0.9hWVY2M-9WTxj9xtwQhfSwVlGJhIBO8OeqTA38T3yRM"
